### ISSUE TITLE
HistoricalDocument not subclassing Document type

### ISSUE THREAD

**Issue by sbor23** [projectcaluma/caluma#1070]
Is there a specific reason why `HistoricalDocument` isn't a subclass of `Document`, like `HistoricalAnswer` subclasses `Answer` and every other type?

https://github.com/projectcaluma/caluma/blob/master/caluma/caluma_form/historical_schema.py#L145

There are cases where this would be convenient, such as visibilities and other extensions would need only one definition for handling both.

**Comment by czosel** [comment]
cc @open-dynaMIX

**Comment by sbor23** [comment]
The reasoning for this can be found in the linked PR.
