### ISSUE TITLE
Wrong sequence names

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#1108]
We once migrated the `caluma_` prefix into all table names (928146577f3cb2f76a4e715ba29ae4e1eb547907) however we didn't consider the sequence names. Maybe we should migrate the sequence names as well to be consistent?

**Comment by sbor23** [comment]
In a fresh database, the following sequences exist:
```
 public | caluma_logging_accesslog_id_seq             | sequence | caluma
 public | caluma_workflow_workflow_allow_forms_id_seq | sequence | caluma
 public | caluma_workflow_workflow_start_tasks_id_seq | sequence | caluma
 public | django_content_type_id_seq                  | sequence | caluma
 public | django_migrations_id_seq                    | sequence | caluma
```
The last two managed by django directly and the rest looks fine.

Is this still a problem in older databases that were migrated?

**Comment by anehx** [comment]
This is only a problem in older databases..
