### ISSUE TITLE
Field for selected option on answer

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#1301]
It would be very convenient to have a field `selected_option` on `StringAnswer` and a field `selected_options` on `ListAnswer` if the answer is linked to a (dynamic) (multiple) choice question.

This would help the user of the API to get the display value in an easy way. For "normal" choices it's possible to get the options relatively easy via the question. However, for dynamic choices the user may need to fetch the `allUsedDynamicOptions` task first and then aggregate those with the current dynamic options which is very cumbersome.

Those new fields would make the usage of the API when using dynamic questions alot less painful.

**Comment by winged** [comment]
Agree, this would be very useful. Not only on GQL level, but also directly on the models

**Comment by sbor23** [comment]
Yes let's do this!

**Comment by open-dynaMIX** [comment]
:+1:
