### ISSUE TITLE
flaky `DynamicOption` schema type

### ISSUE THREAD

**Issue by sbor23** [projectcaluma/caluma#1331]
`DynamicOption`s `question` field is flaky and seems to change it's type on unrelated changes.
Currently it's of type `CalculatedFloatQuestion` which doesn't make sense.
It should be `Question` or a union type of kind:
`union DynamicQuestion = ChoiceQuestion | MultipleChoiceQuestion | DynamicChoiceQuestion | DynamicMultipleChoiceQuestion`

**Comment by winged** [comment]
I think this was resolved by our recent schema fix - was due to a missing import, so the options were only "implicitly" loaded into the schema
