### ISSUE TITLE
Define allowed python versions

### ISSUE THREAD

**Issue by sbor23** [projectcaluma/caluma#1353]
Since caluma can be imported as a package, we should define explicitly which python versions are supported and test those in a CI matrix.

Currently the versions are bit all over the place, there are the following definition in `setup.py`:

* `pipenv install --python 3.7 -r requirements.txt`
* `setup(classifiers=["Programming Language :: Python :: 3.7", ...])` 
* `setup(python_requires=">=3.6, <4")`

We should probably support 3.6 (lts, supported until  2021-12-23) , 3.7, 3.8 and 3.9.

**Comment by open-dynaMIX** [comment]
I agree.

[This workflow](https://github.com/adfinis-sygroup/django-generic-api-permissions/blob/main/.github/workflows/tests.yml) could serve as a template. The `tests` job uses `python: [3.6, 3.7, 3.8, 3.9.0-rc - 3.9]` and runs tox, which in turn tests with Django 2.2, 3.0, 3.1, and latest.

**Comment by anehx** [comment]
This was resolved in #1701 and #1693
