### ISSUE TITLE
Images in Documentation badly visible in Github dark theme

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/caluma#1393]
![Screenshot from 2021-03-01 11-14-09](https://user-images.githubusercontent.com/30687616/109483245-4c089c00-7a7f-11eb-9780-e35595c045c4.png)
 This for example is taken out of https://github.com/projectcaluma/caluma/blob/master/docs/workflow-concepts.md

**Comment by czosel** [comment]
Good point! Probably the easiest fix would be to add a white background to the images.

**Comment by Yelinz** [comment]
Has been resolved with docs webpage
