### ISSUE TITLE
modified_content properties on document

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#1394]
3 new properties should be added to the document:

- `modified_content_at`
- `modified_content_by_user`
- `modified_content_by_group`

Those should return the `datetime`, `user` and `group` of the latest `HistoricalAnswer` record

**Comment by sbor23** [comment]
There is one main issue with using `HistoricalAnswer`: There is `history_date` and `history_user` (which we set correctly) but no `history_group`. Now we could add a new field, hook up a signal to set the group from the request etc. See [docs](https://django-simple-history.readthedocs.io/en/latest/historical_model.html#adding-additional-fields-to-historical-models)

Instead I would propose to use the `modified_at` and add `modified_by_user` and `modified_by_group` to our base class and set it on every model directly, like we do with `created_by...`.
That's actually useful and would make the feature even simpler. This way we could even avoid the history entries completely.

**Comment by anehx** [comment]
I like the idea. @winged @open-dynaMIX @czosel @kaldras what do you guys think about this?

**Comment by czosel** [comment]
Agreed! :+1:

**Comment by winged** [comment]
I concur with @sbor23 - don't rely on `HistoricalAnswer` for this - the feature might be disabled, or historical records might get cleaned up after a while, depending on the actual use case of the installation.

I don't think updating the `Document` at every save of an answer would be too problematic - we'd just have to update the document's family as well (to propagate across tables). Unfortunately this would create historical document entries for every answer save - which could lead to quite a bit more data there that doesn't actually reflect a change in the document model.

Thus, we might also consider read-only fields on the document that basically does `Answer.objects.filter(document__family=self).order_by('-modified_at').first()` and pulls the `modified_*` fields from there. Less redundant data this way, both in storage and in the historical records, and I think it's acceptable performance-wise.

**Comment by sbor23** [comment]
Resolved in #1410
