### ISSUE TITLE
Clean up the connection fields

### ISSUE THREAD

**Issue by winged** [projectcaluma/caluma#1489]
A rather long while ago, we decided to put all the filters into a single `filter` type, per connection. We should now remove the old filter types on the connections, so that we have only the new syntax available.
This should be easily implemented by removing the parent class `filterset_class` from the generated filterset collections in the `CollectionFilterSetFactory`.

At the same time, we should also move the connection types below the top-level ones to the same connection types. For example, the `forms` connection on the `Question` node does not even expose the `filters` field, and thus behaves and looks different to the top-level connections. For example:

```diff
-    forms = DjangoFilterConnectionField(
-        "caluma.caluma_form.schema.Form", filterset_class=filters.FormFilterSet
-    )
+    forms = DjangoFilterConnectionField(
+        "caluma.caluma_form.schema.Form",
+        filterset_class=CollectionFilterSetFactory(
+            filters.FormFilterSet, orderset_class=filters.FormOrderSet
+        ),
+    )
```

**Comment by open-dynaMIX** [comment]
Yes, it's about time, we clean this up.
