### ISSUE TITLE
Keyword: Case families

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#235]
(just like document families)

This will be used to simplify visibility to a tree of cases.

**Comment by sliverc** [comment]
@open-dynaMIX That might be something you could have a look at.

**Comment by sliverc** [comment]
Let's postpone this for now

**Comment by winged** [comment]
I think I will have to dig into this soon - I'll need it for our current project

**Comment by open-dynaMIX** [comment]
Cool, go for it!
