### ISSUE TITLE
node query returns wrong interface type

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#312]
When i create a `TableQuestion` and query it like this
```gql
query TableQuestion {
  node(id: "VGFibGVRdWVzdGlvbjp0YWJsZS1xdWVzdGlvbi0x") {
    id
    __typename
  }
}
```
I get back a TextQuestion:
```
{
  "data": {
    "node": {
      "id": "VGV4dFF1ZXN0aW9uOnRhYmxlLXF1ZXN0aW9uLTE=",
      "__typename": "TextQuestion"
    }
  }
}
```
The same problem occurs for Answers (`StringAnswer` with empty value is always returned, irrespective of actual answer type).

The problem doesn't occur if questions are queried via `allQuestions`.

**Comment by open-dynaMIX** [comment]
This issue is tracked in #432.
