### ISSUE TITLE
Reordering form question fails if archived questions are part of form

### ISSUE THREAD

**Issue by JohnL17** [projectcaluma/caluma#319]
Currently reordering questions in the ember-caluma form builder fails with the error "Input questions are not the same as current form questions" as soon as a question in the form is archived, because the frontend doesn't send the archived question to the backend anymore.

Probably we should ignore archived questions when it comes to reordering. It doesn't really make sense to preserve a specific order for archived questions anymore, does it?

**Comment by czosel** [comment]
As discussed: Let's solve this in the frontend.
