### ISSUE TITLE
Dynamic options in select fields

### ISSUE THREAD

**Issue by fkm** [projectcaluma/caluma#320]
Sometimes, a dropdown field in a form needs to show dynamic content, e.g.

* All groups in the system
* All users in the system
* A reference to a already existing case ID in caluma ("linking")

-> The data for the options can come from internal or external data sources / APIs. Maybe we can consider "registering" custom option providers in Caluma as an extension point. These providers can then, using the full power of python,

* make API calls and parse responses
* access data inside the caluma DB
* something else we can't imagine yet :wink:

**Comment by czosel** [comment]
More detailed design:

* Naming: `DataSource` / `KeyValueDataSource`

```python
def my_helper():
  # no prefix, will not be autodiscovered

def data_source_active_groups(): # autodiscovery based on data_source_ prefix
  # make some API requests or whatever
  return data # Iterable (either key-value pairs or just values)
```

* Docker: `DATA_SOURCES: caluma.extensions.data_sources.my_custom_data_sources`
* Options should be always "up-to-date" -> Always re-run data source code when options are requested
* Caching: Solve inside caluma or in user-land? Idea: Simple decorator like 
```py
import cache from caluma-data-source/caching
@cache(10) # cache with lifetime of 10 seconds
def ...
```

* new question types: `DynamicChoiceQuestion`, `DynamicMultipleChoiceQuestion`
  * `SaveDynamic_(Choice/MultipleChoice)_Question` Mutation takes new parameter `dataSource`: `String!`

* Queries:
  * `allDataSources`
