### ISSUE TITLE
Filter cases by status

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#321]
Title pretty much says it all.

This will be very usefull for intervalled forms.

**Comment by czosel** [comment]
This seems to work already, see the `status: CaseStatusArgument` field on the `allCases` query. I added a test in #331 that confirms this.

**Comment by open-dynaMIX** [comment]
This was a misunderstanding on my side. I wanted to do something which will not be possible. Still getting familiar with graphql :wink: 

Let's talk about it in person.
