### ISSUE TITLE
Remove RemoveOption mutation

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#339]
We noticed in code review that this mutation seems unsafe (referenced answers, cascading).

**Comment by sliverc** [comment]
Issue in this case is that the question option reference will also be deleted.

Currently there is no OptionAnswer but when thinking about it potentially this needs to be thought through especially in case of multi language options.

**Comment by open-dynaMIX** [comment]
As discussed in person:

We will remove the `removeOption` mutation.

See #603.
