### ISSUE TITLE
Wrong type of `parentAnswers` of the `Document`-type

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#382]
Since the merge of #353 the type of `parentAnswers` of the `Document`-type is `[FileAnswer]` but should be `[FormAnswer]`:

```
type Document implements Node {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdByUser: String
  createdByGroup: String
  id: ID!
  form: Form!
  meta: JSONString!
  answers(before: String, after: String, first: Int, last: Int, question: ID, search: String, createdByUser: String, createdByGroup: String, metaHasKey: String, orderBy: [AnswerOrdering]): AnswerConnection
  parentAnswers: [FileAnswer]  # <---
  case: Case
  workItem: WorkItem
}
```

Somehow, this is due to the order of declaration of the Answers in the schema.

If the declaration of `FormAnswer` is moved below the declaration of `FileAnswer`, then this ist fixed, but then the type of the answer of `File` is changed as well:

```
type File implements Node {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdByUser: String
  createdByGroup: String
  id: ID!
  name: String!
  answer: FormAnswer  # <--
  uploadUrl: String
  downloadUrl: String
  metadata: GenericScalar
}
```

The types should not depend on the order of declaration, but be set explicitly.

**Comment by czosel** [comment]
Wow, that's pretty strange. Looks a bit like a bug in graphene. I'd be ok with just leaving this documented for the moment though - we can try to create a minimal reproduction and open an issue in graphene about this in the future.

**Comment by open-dynaMIX** [comment]
#424 caused a regression and had to be reverted (#429).

**Comment by open-dynaMIX** [comment]
This issue is tracked in #432.
