### ISSUE TITLE
Add dot to filename of download

### ISSUE THREAD

**Issue by fkm** [projectcaluma/caluma#387]
Currently, the filename of the download is missing the dot before the file extension.

So "foo.docx" becomes "foodocx". In that example, KDE is opening the file with Ark as docx files are indeed archives.

**Comment by open-dynaMIX** [comment]
The reason for this is that the object name is slugified. I guess this is unnecessary, but if we don't do that, the UUID will still be part of the object name.

You can ask for the original filename in the query:

```
... on FileAnswer {
  fileValue: value {
    name
    downloadUrl
    metadata
  }
}
```

I will still remove the slugification, but recommend using the original name to present to the user.
