### ISSUE TITLE
UUID vs auto-incrementing PKs

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#390]
As far as I remember, we originally decided to use UUIDs everywhere for the following reasons:

1. Avoid ID collisions / merge conflicts when database-driven configuration is created by multiple developers locally
2. UUIDs can't be guessed, which might be preferable in some scenarios from a security point of view
3. UUIDs simplify some migration scenarios, because they don't collide

Advantage (1) we solved by using slugs as PKs (Form, Question, Workflow, Task), currently we only have UUIDs for models that we don't consider as "configuration" (exception: `Flow`)

At the same time, the length of UUIDs comes with some disadvantages:

- They are not useful as reference keys in a user interface
  - In one of our projects we currently need a simple auto-incrementing ID on the `Case` entity. In other systems, I could imagine the same requirement for `Document`, and maybe also `WorkItem`. I don't see that we'd ever need it for `Answer`.
- They are a bit harder to handle during development

I see the following options:

- use auto-incrementing PKs for entities that really need it right now (pretty much only `Case`)
- use auto-incrementing PKs for more entities (Case, Document, WorkItem)
- make use of auto-incrementing PKs configurable (per entity?)
- keep the UUIDs everywhere, but engineer something that allows having an additional "pseudo"-PK that supports all the filtering, indexing etc. that we expect from a "true" PK.

I'm sure I'm missing some considerations in this breakdown, so I'm really happy to get your feedback!

@sliverc @winged @kaldras @open-dynaMIX

**Comment by czosel** [comment]
@sliverc We discussed this offline, and came to the conclusion that we'll implement this in a separate service; similar to what we discussed when this first came up. We'll add more details about the implementation here soon.

**Comment by sliverc** [comment]
@czosel 
As I remember such a service might be quite a bit of work.

I would see another fairly simple option you currently haven't listed - a validation class for start case. This could be custom class per project and if it covers several use cases an example class within Caluma.
Unique id could be written to meta and for thread safety database locking could be used.
This is easier implemented and might just be as good as an external service.
Just a thought.

**Comment by czosel** [comment]
@sliverc Thanks for the suggestion :slightly_smiling_face: 

One question though: The validations run before the mutation is performed - so there is no `Case` object yet where we could write `meta` to. We've been thinking about a new custom layer (called `side_effects`) where users could inject code that runs _after_ mutations, but were not convinced about it because it promotes tight coupling between services and the customization layers are generally something we don't want to overuse.

Alternatively, it would be nice if it we could "enrich" the incoming graphql string before sending it to the serializer (e.g. adding `meta` data) - but AFAIK that's not possible without hacking the graphql AST.

**Comment by sliverc** [comment]
side effects can be done with validation classes as well.

Even though they are called validation classes validate methods return a data dict which contains all the data which an object is created or updated with. That's a Django REST Framework serializer concept and there its also called validation.

See https://github.com/projectcaluma/caluma#validation-classes

Short snippet:
```python
class CustomValidation(BaseValidation):
    @validation_for(SaveCase)
    def validate_mutation(self, mutation, data, info):
        data['meta']['sequence'] = 'calculated sequence'
        return data
```

**Comment by czosel** [comment]
Right - I must have confused this with something else. I'll give this a shot, thanks a ton! :+1:

**Comment by sliverc** [comment]
@czosel As this can be done with validation classes do you think we can close this?

**Comment by czosel** [comment]
Absolutely!
