### ISSUE TITLE
Add "intersects" operator to JEXL

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#406]
This would help with checking if a MultipleChoice question has at least one of the given options checked, which is a common use-case:
```
"my-multiple-choice-question"|answer intersects ["answer-a", "answer-b"]
```
JS Implementation:
```
questionJexl.addBinaryOp("intersects", 20, (left, right) => left.find(val => right.includes(val)))
```

**Comment by winged** [comment]
I like the idea! However the JS implementation is a bit buggy - what if we're dealing with a falsy value so the `intersects` operator "succeeds" but then returns the falsy bit? `some()` seems to be better suited.

```js
questionJexl.addBinaryOp("intersects", 20, (left, right) => left.some(val => right.includes(val)))
```

**Comment by czosel** [comment]
Absolutely, good catch! I've hacked this line in a bit of a rush yesterday :wink:
