### ISSUE TITLE
Enable automerge for renovate for certain dependencies

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#442]
Renovate is very noisy and occupies our available pipelines.

We want to enable auto-merge for following dependencies:

* python:3.6 Docker image
* postgres:9.6-alpine Docker image

**Comment by open-dynaMIX** [comment]
@czosel @winged Should we also auto-merge dev dependencies (at least patch and minor updates)?

**Comment by winged** [comment]
> @czosel @winged Should we also auto-merge dev dependencies (at least patch and minor updates)?

Absolutely! I'd even go as far to say the dev dependencies are less critical to auto-update

**Comment by open-dynaMIX** [comment]
Enabling auto-merge will need [this app](https://github.com/apps/renovate-approve) in order to get it's PRs approved.

**Comment by czosel** [comment]
:+1: I'd also prefer auto-updating dev deps for our JS repositories. Can you have the necessaray priviledges to enable the approve app?

**Comment by open-dynaMIX** [comment]
> Can you have the necessaray priviledges to enable the approve app?

Yes, it's installed. But I only enabled it for the backend for now.
