### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#477]
Currently if the client is not authenticated we get a 200 status code with this response body:

```json
{
   "errors":[
      {
         "message":"401 Client Error: Unauthorized for url: http://keycloak.local/auth/realms/ebau/protocol/openid-connect/userinfo",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "path":[
            "allCases"
         ]
      }
   ],
   "data":{
      "allCases":null
   }
}
```

Wouldn't it make more sense to send an actual 401 response?

**Comment by open-dynaMIX** [comment]
Of course! It's already [planned](https://github.com/projectcaluma/caluma/blob/master/caluma/user/middleware.py#L26) :wink:

**Comment by sliverc** [comment]
See https://github.com/graphql-python/graphene-django/issues/252 which has an example how to do this. Needs to be evaluated whether this works for us as well.
