### ISSUE TITLE
Answers to FormQuestions must be flat

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#504]
There was a conceptual misunderstanding that led us to implement
nested answers in FormQuestions. This created performance and complexity
issues.

The discussion about this started in #489 and the following telco made it evident, that we have to revert this.

Answers to sub-questions of FormQuestions must remain flat. In turn this means, a Question can only once be answered per document and all answers in a case share the same document.

This makes the FormAnswer type obsolete.

**Comment by czosel** [comment]
:+1: 

(except table questions :wink: )

**Comment by open-dynaMIX** [comment]
Absolutely, I have clarified it.

**Comment by anehx** [comment]
> In turn this means, a FormQuestion can only once be answered per document and all answers in a case share the same document.

And what will the answer to such a FormQUestion be exactly?

**Comment by open-dynaMIX** [comment]
The FormQuestion has no direct answer anymore.

**Comment by anehx** [comment]
Alright, and I guess answers to form questions will be prefixed with the form slug?

**Comment by open-dynaMIX** [comment]
No, as soon as the answers to sub-questions of a FormQuestion are flat, we don't have any nesting and don't have to reference the form anymore. A question can not be answered multiple times per document. No matter if it's in a sub-form.

**Comment by anehx** [comment]
So what if two sub forms have the same questions?

**Comment by open-dynaMIX** [comment]
Then they have the same answer.
