### ISSUE TITLE
Filters on allCases graph

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#545]
We need some filters on the `allCases` graph

- [x] `document.form.slug`, filtering by form type
- [x] `metaValue` needs new lookup types `GT`, `GTE`, `LT`, `LTE`
- [x] `metaValue` can take multiple filters
- [x] Search over multiple `hasAnswer` filters

**Comment by winged** [comment]
* Document form slug: #548 
* metaValue GT & friends: #547 
* metaValue multiple filters: #544 
* multiple hasAnswers: was implemented a long time ago (#430)

**Comment by winged** [comment]
Closing as all requirements have been solved
