### ISSUE TITLE
Make ordering by meta field dynamic

### ISSUE THREAD

**Issue by sliverc** [projectcaluma/caluma#616]
Currently meta ordering is very static as someone needs to define `META_FIELDS`. Caluma allows all meta keys to be added without any configuration so sorting should do the same.

For this to work we could introduce `orderByMeta` with a custom type like `MetaValueFilterType` where api user defines key name to sort and descending or ascending.

**Comment by sliverc** [comment]
We might also consider removing `META_FIELDS` from documentation as once we release it we might not want to support this feature in the future.

**Comment by czosel** [comment]
@winged so this is working now? Is there something in the release notes about it?

**Comment by winged** [comment]
@czosel Oliver already removed `META_FIELDS` as visible from the referenced PRs.

Introduction of the new `meta` ordering was done in #724 and released v2.0.0

**Comment by czosel** [comment]
Awesome, thanks!
