### ISSUE TITLE
Expose historical tables on API

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#650]
It would be nice if we'd have some queries that allow accessing the historical data that we're recording. This probably needs some more detailed design before we jump into implementation.

/cc @open-dynaMIX @winged

**Comment by winged** [comment]
To my current understanding, we want to use this to view "old versions of a document" or "old versions of a case". To avoid query explosions, I suggest a new node under allDocuments to access historical data.

Since the frontend writes all the time during editing, we also need some filtering / sanitizing so we can filter out intermediate versions, as they won't be useful for the users. How exactly we're going to group it I don't know yet.

@czosel what are the current wishes / requirements from the user persepctive? Are we looking at it from a per-form perspective? -> will we need filters on question slugs? 

Do we want a per-question history, or do we want a time-indexed history of changes to the document? I gather this could be really interesting too frontend-wise, as you could implement a slider over time to see all the changes being applied/edited etc..

**Comment by open-dynaMIX** [comment]
> Since the frontend writes all the time during editing, we also need some filtering / sanitizing so we can filter out intermediate versions, as they won't be useful for the users. How exactly we're going to group it I don't know yet.

Maybe we should move away from automated saving to the history and instead actively write to it based on certain triggers. Not sure if this is doable though, as some forms are not necessarily submitted after editing.

**Comment by winged** [comment]
After a bit of thinking, I figure we could generate some kind of versioning by looking at the distribution of edits:

* Let's define a minimum duration between versions of 2 hours.
* When sorting all edit events per document, we can iterate over them and "trigger" a version each time there's more than said 2h between an event (across questions!).
* The timestamps of those versions can then be used to query the historical versions at that given time

A first hacky attempt on SQL level for this:
```sql
SELECT
    ha.document_id,
    ha.question_id,
    ha.created_at,
    CASE WHEN min(ha_future.history_date)
        IS NULL THEN
        FALSE
    ELSE
        TRUE
    END AS has_future_rev
FROM
    form_historicalanswer ha
    LEFT JOIN form_historicalanswer ha_future ON ha.document_id = ha_future.document_id
        AND ha.question_id = ha_future.question_id
        AND ha_future.history_date BETWEEN ha.history_date
        AND ha.history_date + interval '2 hour'
        AND ha.id != ha_future.id
    GROUP BY
        ha.created_at,
        ha.document_id,
        ha.question_id;

```

**Comment by czosel** [comment]
Our current use case is a "history" view of a specific document that would summarize the changes to all the questions of the documents and might look like this:

| Date  | User | Change |
| ------------- | ------------- |  ---- |
| 1.1.2019  | Dave  | Description: "my application" -> "My Application" |
| 2.1.2019  | Fabio  | Is interested: "no" -> "yes", E-Mail: "fabio@example.com" -> "fabio@example.net" |

**Comment by winged** [comment]
Here's an improved version of the query, which (almost) gives you the required information. Still "debounced" for a 2-hour period, but it could easily be changed to group changes by day, for example.

```sql
SELECT
    *
FROM (
    SELECT
        ha.created_by_user,
        ha.document_id,
        ha.question_id,
        ha.created_at,
        ha.value,
        CASE WHEN min(ha_future.history_date)
            IS NULL THEN
            FALSE
        ELSE
            TRUE
        END AS has_future_rev
    FROM
        form_historicalanswer ha
    LEFT JOIN form_historicalanswer ha_future ON ha.document_id = ha_future.document_id
        AND ha.question_id = ha_future.question_id
        AND ha_future.history_date BETWEEN ha.history_date
        AND ha.history_date + interval '2 hour'
        AND ha.id != ha_future.id
    GROUP BY
        ha.created_at,
        ha.document_id,
        ha.question_id,
        ha.created_by_user,
        ha.value
    ORDER BY
        ha.created_at) rev
WHERE
    rev.has_future_rev = FALSE
    AND rev.document_id = '44dde6f5-5fc9-47e6-a436-e9603292123a';
```

On my test DB, this gives the following output:

```
           created_by_user            |             document_id              |              question_id              |          created_at           |               value               | has_future_rev 
--------------------------------------+--------------------------------------+---------------------------------------+-------------------------------+-----------------------------------+----------------
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | ort-gesuchstellerin                   | 2019-08-14 14:28:00.592643+00 | "ljlk"                            | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | nummer-gesuchstellerin                | 2019-08-14 14:28:01.627913+00 | "ökjöjl"                          | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | strasse-gesuchstellerin               | 2019-08-14 14:28:01.89945+00  | "jlj"                             | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | vorname-gesuchstellerin-vorabklaerung | 2019-08-14 14:28:02.687827+00 | "jklkj"                           | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | name-gesuchstellerin-vorabklaerung    | 2019-08-14 14:28:02.97616+00  | "lkj"                             | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | gemeinde                              | 2019-08-14 14:28:12.047891+00 | "2"                               | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | gemeinde                              | 2019-08-14 14:28:12.047891+00 | "20017"                           | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | anfrage-zur-vorabklaerung             | 2019-08-14 14:30:59.667375+00 | "lkjlkjlkj"                       | f
 855a5ba0-cdcc-48d5-ab7c-4fc55cbe0754 | 44dde6f5-5fc9-47e6-a436-e9603292123a | einreichen-button                     | 2019-08-14 14:32:12.226772+00 | ["einreichen-button-eingereicht"] | f
```
