### ISSUE TITLE
Cancel / Skip Work items

### ISSUE THREAD

**Issue by fkm** [projectcaluma/caluma#676]
When using multiple instance tasks, it is currently impossible to cancel / force-close a created work item. In one of our projects this would be desired, when a work item has been created by accident. In this situation we'd like to "cancel" or "skip" the work item, meaning that it is either completed without validations or transfered to a new status (e.g. "cancelled" or similar). For the workflow, this state would be handled the same way as when the workitem is completed (just without running validations). This would probably require a new mutation, e.g. "CancelWorkItem".

Thoughts?
/cc @winged @open-dynaMIX @kaldras @czosel

**Comment by czosel** [comment]
ping @winged @open-dynaMIX @kaldras

**Comment by winged** [comment]
Note regarding the implementation: [WCP26](http://www.workflowpatterns.com/patterns/control/new/wcp26.php) mentions cancelling the whole Task, meaning all sibling instances.
@czosel and me feel like skipping single instances gives us more flexibility by being able to cancel/skip single work items. To comply with WCP26, we can still do that by simply looping client-side if needed.

I'm going to do a `SkipWorkItem` mutation, accompanied with a new work item state to indicate this

**Comment by czosel** [comment]
cc @kaldras @open-dynaMIX @sliverc

**Comment by open-dynaMIX** [comment]
I agree.
