### ISSUE TITLE
orderByQuestionAnswerValue on allWorkItems

### ISSUE THREAD

**Issue by fkm** [projectcaluma/caluma#698]
I need the possibility to sort by answers to questions attached to the document which is attached to the case.

Preferably, this would work work even if the work-item is not directly attached to the case but through a `childCase`. But that is not something I need at the moment.

In essence, I need the same thing we currently have for `allCases`. From a nesting standpoint it will probably be similar to `caseDocumentHasAnswer` and `caseMetaValue`.

I recommend we consider dynamic nesting through child cases (or parent work-items) at a later time for all the relevant filters.

**Comment by winged** [comment]
this is fixed in #724

**Comment by winged** [comment]
@fkm can you verify that #724 solves your need?

**Comment by fkm** [comment]
Thank you!
