### ISSUE TITLE
Set UID env variable for "user" option at first start

### ISSUE THREAD

**Issue by loleg** [projectcaluma/caluma#739]
On first run following your README with the v1.0.0 release, I got this error:

```
HEAD is now at cdbaf60 Merge pull request #691 from projectcaluma/renovate/urllib3-1.x
[oleg@localhost caluma]$ docker-compose up 
ERROR: Missing mandatory value for "user" option in service "caluma": Set UID env variable to your user id
```

I saw no mention of this variable in the [INSTALL](https://github.com/projectcaluma/caluma/blob/master/docs/guide.md) or [Configuration](https://github.com/projectcaluma/caluma/blob/master/docs/configuration.md) docs. Running this code snippet from the Travis configuration solved the issue quickly:

`echo "UID=$(id --user)" > .env`

... but this should be defaulted or documented. I'm on a pretty standard Fedora Core 30 workstation.

**Comment by loleg** [comment]
Sorry, I was half listening to your session at DINAcon and not reading the instructions properly. It's not completely unexpected but still a bit strange to have to create a blank folder with a Docker configuration to test the software. This worked without a hitch. So it's not that your instructions are completely wrong, you just might want to make a clear statement like "before you try to run this from the source root folder..see additional instructions here".

Also there's a slightly confusing and possibly not meaningful discrepance in the docs:
```
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -23,7 +23,7 @@ services:
     environment:
-      - ENV=dev
+      - ENV=development
```

**Comment by czosel** [comment]
@loleg Sorry we took so long to fix this - should be good now. Thanks again for bringing up the issue!
