### ISSUE TITLE
Form validation: isHidden behaves differently than in the frontend

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#781]
In the frontend implementation, we don't even evaluate a question's `isHidden` JEXL if all the fields it depends on are hidden themselves.

Example:

Question 1 is always visible
Question 2 is hidden when Q1 == "foo"
Question 3 is required and hidden when Q2 == null

This currently leads to the frontend hiding Q3 and not validating it's requiredness (because Q2, it's only dependant, is hidden), while the backend would think that it's displayed and validate it's requiredness.

**Comment by winged** [comment]
@czosel please check if it works as expected now
