### ISSUE TITLE
Rethink caching strategy for datasources

### ISSUE THREAD

**Issue by kaldras** [projectcaluma/caluma#793]
The language code is not within the cache-key. This could lead to problems when caching is activated and therefore should be looked at again. For example:

The datasource translates its own values. Fetch the values in "de", cached for 30 seconds and switch to "fr" within these 30 seconds. Caluma will then return the cached "de" values since the same key for this datasource is used.

**Comment by open-dynaMIX** [comment]
I assume there is another problem, as the datasource caches the whole return value of `get_data()` and not just the value with it's translated label. So the translation should not be affected by the caching at all.

Translation must not happen in the DataSource. `get_data()` must return all available translations per option. Translation is done when fetching the data from it and follows the same logic as the `LocalizedField()`.

**Comment by open-dynaMIX** [comment]
Resolved by #797
