### ISSUE TITLE
Validation of unanswered file questions failed

### ISSUE THREAD

**Issue by JohnL17** [projectcaluma/caluma#800]
I have a non required file question in a form. When the form was validated and the question is unanswered I get the following error message:
![image](https://user-images.githubusercontent.com/21102692/69053210-2df16680-0a09-11ea-91e5-8bb95b5114ba.png)

**Comment by open-dynaMIX** [comment]
There is a fix for this in #791 : https://github.com/projectcaluma/caluma/pull/791/files#diff-3971631935db9deda08b7d29a84754c7L252

I hope this can be merged today.
