### ISSUE TITLE
Table question JEXL

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#870]
JEXLs in table question should be able to access the "parent documents" (same family) answers.

This is already implemented in the frontend: https://github.com/projectcaluma/ember-caluma/pull/726

**Comment by anehx** [comment]
Doesn't work :angry:

**Comment by anehx** [comment]
After some further testing I discovered the case in which this doesn't work properly: If you have a table which contains a question using a jexl "answer" transform to a question of the outer form and add a row of said table. Which means: the structure does not compute the parent correctly when linking the table row with the parent document.

@winged

**Comment by winged** [comment]
Documenting the off-line discussion from this morning:

We agree that validation of the row document at the moment of "insertion" is not the right way to go: It makes row documents special, as they have to be valid during the "editing phase", when every other part of the whole document ("family") doesn't need to be. In all other places, we allow saving answers without regards to their validity (apart from obvious things like selected options in [multiple] choice questions). Treating table answers specially here is not intuitive for the user, and makes the code more complex.

In addition, unlinking and linking of row documents won't need to happen if we loosen this restriction, making the code even more simple (and the behaviour more intuitive). This will also help with reducing the stale row documents in the database.

Ideally, we'd also create a new mutation to link-and-create a row document in one go, so we don't have to worry about stale rows at all anymore. However this is orthogonal to the issue at hand and can be solved later.

So, here's the updated task:

* Don't do validation at link time anymore
* Don't do the unlink/link cycle anymore
