### ISSUE TITLE
Why is family not a FK?

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#910]
I was wondering why the `family` field on the document model is a `UUIDField` not a `models.ForeignKey("self")`? We have various use-cases now where we'd like to join the family document by ORM but have to do a subquery instead.

No one present could tell me why (:notes:) this is not an FK - can someone? @sliverc @winged @open-dynaMIX

**Comment by sliverc** [comment]
I have a feeling this simply hasn't been thought off when the family concept was created and it could just as well be a foreign key.

**Comment by winged** [comment]
I'm still trying to think through all the implications. I sort of remember that we consciously decided against it but can't remember the reason at all.

But again, I think if we can't remember the reason and can't think of why it would be a bad thing, we should probably make it an FK. Would also allow us to have a reverse `family_members` or similar to get all related documents
