### ISSUE TITLE
Add caluma to PyPI

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#940]
We've decided to add caluma to the python package index (PyPI).

I've already uploaded a package to https://test.pypi.org. It can be found [here](https://test.pypi.org/project/caluma/).

Here's how to install it with pip:

```shell
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple caluma
```

TODOs:

- [x] Verify everything works as expected.
- [ ] Verify all necessary files are added to the source dist (`MANIFEST.in`).
- [ ] Use absolute URIs in the documentation, so that the links are also working in PyPI. Or use a dedicated markdown file for PyPI.
- [x] Create a CI job for automatically building and uploading caluma when a new tag is created.
- [x] Add documentation about usage of caluma apps outside of the caluma service

Related issues and PRs:

* #938 
* #939 
* #941
* #946 
* #947 
* #950
* #951 
* #953 
* #954 
* #959

**Comment by winged** [comment]
Closing, this has been completed for a while now :)
