### ISSUE TITLE
Document API available from extension points

### ISSUE THREAD

**Issue by winged** [projectcaluma/caluma#941]
This discussion came up during PR #935. I agree we should address this in the documentation to let people know exactly what interfaces should be stable from within extension points, and which ones are likely to change.

---

> Discussion: The family was kind of intended to be non-public from Caluma's perspective, but is still used in customer project's permissions / visibility layers.

Related idea to this, I think it would help to define the API that is officially supported to be used in extensions. This should be documented, so that it's obvious for all users. 

Usage of modules outside of the defined API should still be possible, but they might be subject to change.

Right now it's not really possible to write extensions without reading the caluma source. Documentation of those modules would help new users to get started.

> Due to this change, this PR would possibly need to be escalated to "breaking" - what do you guys think?

I agree.

_Originally posted by @open-dynaMIX in https://github.com/projectcaluma/caluma/pull/935#issuecomment-588061140_

**Comment by open-dynaMIX** [comment]
This becomes even more relevant when we have caluma in PyPI.
