### ISSUE TITLE
"controlling" for Tasks and WorkItems

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#969]
# Rationale

Caluma is a system where people organise their work based on tasks. For many tasks, it is desirable to have a controlling instance.

Analogous to `address_groups`/`addressed_groups`, we propose a `controlling` JEXL on `Task` that evaluates to a list of `controlling` groups on `WorkItem`.

Further, we propose to expand the evaluation context for the JEXL evaluation.

## What does Caluma do with `controlling_groups`?

Caluma will happily evaluate the `control_groups` jexl in order to set the `controlling_groups`. For multiple instance tasks, it's also possible to provide a list of `controlling_groups` to the `createWorkItem` mutation.

There are no built-in controlling tasks or workflows. But with the extended group jexl, it's possible to address work items to groups that had a controlling function on the previous work item.

## Extending the JEXL context

There is a new object `info` as variable in the group jexl context.

We propose following new variables:

```python
{
    "info": {
        "case": {
            "created_by_group": str,
        },
        "work_item": {
            "created_by_group": str,
        },
        "prev_work_item": {
            "controlling_groups": list of str,
        },
    },
}
```

The values can be accessed in the jexl expression through dot-notation. For example:

`info.case.created_by_group`

### `info.work_item.created_by_group`

This is useful to assign the group that started a work_item as controllers.

### `info.case.created_by_group`

Same as above, but use the group that started the case.

### `info.prev_work_item.controlling_groups`

Let's say you have a work_item "A", that has group "G" assigned as controlling group.
When the work_item is finished, you want to start a "controlling" work_item "B" addressed to
the controlling group "G" of the work_item "A".

This can be achieved if you set `address_groups` of the `Task` for work_item "B" to `work_item_controlling_groups`. This will then correctly evaluate to group "G".

**Comment by czosel** [comment]
Can you add some details about what should be added to the evaluation context?
