### ISSUE TITLE
Add name and description to WorkItems

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#988]
# Rationale

Our goal is to be able to dynamically start `WorkItems` based on a generic `Task`, that can be manually assigned to groups.

For this we need the possibility to set our own `name` and `description`.

## Proposal

We propose to add two new fields to the `WorkItem` model:

1. `name`
2. `description`

If not explicitly set, those should inherit their values from the `Task` instance.

Additionally we need the same two fields on the `saveWorkItem` and `createWorkItem` mutations.

**Comment by winged** [comment]
Not sure if just a mistake, but first you talk about `name` and `description`, then about `name` and `title`, which in my mind doesn't make as much sense.

Adding `name` and `description` with the behaviour you describe is a good idea though, in my opinon

**Comment by open-dynaMIX** [comment]
Oops! Of course we inherit the names of the fields from the Task model. It's fixed in the description.
